### ISSUE TITLE
Support for Connections API

### ISSUE THREAD

**Issue by ryno1234** [kinde-oss/kinde-dotnet-sdk#17]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

I would like to be able to call the Connections endpoints 

### What solution would you like to see?

Implementation of these API endpoints

**Comment by coel** [comment]
Just cleaning up issues, I believe this has since been added.  Feel free to reopen if there is still an issue.
