### ISSUE TITLE
Support for additional Application fields such as login URI and homepage URI

### ISSUE THREAD

**Issue by ryno1234** [kinde-oss/kinde-dotnet-sdk#18]
### Prerequisites

- [X] I have searched the repository’s issues, [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) and [public roadmap](https://updates.kinde.com/board) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Would like to be able to set all the properties of an Application, but namely the associated URIs.

### What solution would you like to see?

Implement the full model

### Additional information

Example of fields:

![image](https://github.com/kinde-oss/kinde-dotnet-sdk/assets/92051/009b2ae5-4337-4521-801f-ecabe23e436f)

**Comment by coel** [comment]
Just cleaning up issues, I believe this has since been added.  Feel free to reopen if there is still an issue.
